# Generated by Django 4.1.5 on 2023-02-14 07:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_portal"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Portal",
        ),
    ]
